export const KEYDOWN = 'KEYDOWN';
export const KEYUP = 'KEYUP';
export const TRANSLATE_CANVAS_START = 'TRANSLATE_CANVAS_START';
export const TRANSLATE_CANVAS = 'TRANSLATE_CANVAS';
export const TRANSLATE_CANVAS_END = 'TRANSLATE_CANVAS_END';

export const CLICK = 'CLICK';

export const ADD_TILES = 'ADD_TILES';
export const REMOVE_TILES = 'REMOVE_TILES';