export const KEYDOWN = 'KEYDOWN';
export const KEYUP = 'KEYUP';
export const TRANSLATE_CANVAS_START = 'TRANSLATE_CANVAS_START';
export const TRANSLATE_CANVAS = 'TRANSLATE_CANVAS';
export const TRANSLATE_CANVAS_END = 'TRANSLATE_CANVAS_END';

// export const CLICK_TILE = 'CLICK_TILE';

export const ADD_TILE = 'ADD_TILE';
export const REMOVE_TILE = 'REMOVE_TILE';